language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.mvn/wrapper/
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN
      
script:
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
