spring:
  profiles:
    active: dev
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: boot
#  cloud:
#    stream:
#      binder:
#        brokers:
#        defaultBrokerPort:
#        zkNodes:
#        defaultZkPort:
#  cloud:
#    stream:
#      bindings:
#        output:
#          destination: transformed
#        input:
#          destination: testtock

#cron:
#  calculate:
#    score: 0 0/1 * * * ?
#  check:
#    orders:
#      expired: 0 0/1 * * * ?

spring:
  data:
    mongodb:
      database: dev
